---
title: "coding challenge 4_markdown"
author: "Radhika"
output: 
 
 word_document: 
 html_document:
  toc: TRUE
  number_sections: true
  toc_float: true
  md_document:
    variant: gfm
   


date: "2026-02-19"
---
# . Explain

  a) YAML header: YAML contains the arguements like title, author, date demarcated by three dashes --- on both ends. this is displayed at the begining of the document. 
 
  b) Literate programming : Literate programming is a method of writing code integrated with explanatory documentation in a single reproducible document.
 
# . Question 

[data for the manuscript is here.](https://doi.org/10.1094/PDIS-06-21-1253-RE)
 
```{r coding challenge 2 question 5 read file}
df<- read.csv("MycotoxinData.csv", na.strings = "na")

```
 
 
 
 
 
```{r DON data}
library(ggplot2)
plot_box<- ggplot(df, aes(x = Treatment, y= DON, fill= Cultivar))+
  geom_boxplot()+
  scale_fill_manual(values = c("#0072B2","#E69F00"))+
  geom_point( position= position_jitterdodge(), color="black", alpha= 0.6)+
  xlab("")+
  ylab("DON (ppm)")+
  facet_wrap(~Cultivar)+
  theme_classic()
  
plot_box

```
```{r 15ADON}
plot_X <- ggplot(df, aes(x = Treatment, y= X15ADON , fill= Cultivar))+
  geom_boxplot()+
  scale_fill_manual(values = c("#0072B2","#E69F00"))+
  geom_point( position= position_jitterdodge(), color="black", alpha= 0.6)+
  xlab("")+
  ylab("15ADON")+
  facet_wrap(~Cultivar)+
  theme_classic()
plot_X

```
 
```{r Seedmass}
Plot_M<- ggplot(df, aes(x = Treatment, y= MassperSeed_mg , fill= Cultivar))+
  geom_boxplot()+
  scale_fill_manual(values = c("#0072B2","#E69F00"))+
  geom_point( position= position_jitterdodge(), color="black", alpha= 0.6)+
  xlab("")+
  ylab("Seed Mass (mg)")+
  facet_wrap(~Cultivar)+
  theme_classic()

Plot_M
```
```{r arranging all, warning=FALSE}
library(ggplot2)
library(ggpubr)
P1<-plot_box +
  geom_pwc(aes(group = Treatment ),method = "t_test", label = "p.adj.format")
P2<-plot_X + 
  geom_pwc(aes(group = Treatment ),method = "t_test", label = "p.adj.format")
P3<-Plot_M+
  geom_pwc(aes(group = Treatment ),method = "t_test", label = "p.adj.format")
# ARRANGING ALL IN  1 FIGURE
fig2 <- ggarrange( plotlist = P1, P2, P3, 
                   labels ="auto",
                   nrow = 1, 
                   ncol = 3,
                   common.legend = T
)
fig2 
```
 
 
 [github repository link](https://github.com/Radhika-ri/reproducibility/tree/main)
 
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


